### ISSUE TITLE
How to use this package?

### ISSUE THREAD

**Issue by Kaju-Bubanja** [AIT-Assistive-Autonomous-Systems/ros2bag_tools#1]
I downloaded the repo into src/util/ros2bag_tools. Then I used following command: `colcon build --symlink-install --packages-select rosbag2_tools` the package successfully builds in 3.73s and then I resource the workspace. but when trying `ros2 bag export` I get: Usage error invalid choice 'export'. Like the verb doesn't exist. I'm using Ubuntu 20.04 and Ros rolling.

**Comment by jeremy-shannon** [comment]
It _would_ be helpful to put some detailed installation instructions in the readme.

**Comment by devrite** [comment]
Hi @jeremy-shannon,

regarding install: please open an issue if any ros specific dependencies are missing in the `package.xml`. Otherwise it is the same procedure as already officially documented for building workspaces or installing dependencies via rosdep. See: https://docs.ros.org/en/rolling/Tutorials/Beginner-Client-Libraries/Creating-A-Workspace/Creating-A-Workspace.html#resolve-dependencies.

**Comment by cynosure4sure** [comment]
I think the confusion is that there are two packages inside the `ros2bag_tools` folder, namely `ros2bag_tools` and `rosbag2_tools` (notice the position of 2). If you do `colcon build --packages-select ros2bag_tools` it will fail because the other one needs to be build first so `colcon build --packages-select ros2bag_tools rosbag2_tools` should do the trick
